### ISSUE TITLE
Integration: necessary files into deploy folder

### ISSUE THREAD

**Issue by EduJGURJC** [elastest/elastest-data-manager#3]
Hi,

In relation with [ElasTest components integration](https://docs.google.com/document/d/1EeqyYQOWkRA0FNLsvYOxWtteV-u3O1Fp1bJKFsfwS80) and considering what was discussed in [Issue 1](https://github.com/elastest/elastest-data-manager/issues/1) it's necessary to copy some files into deploy folder for start EDM.

Could you copy these files?

Thanks in advance

**Comment by sgioldasis** [comment]
Hi,

I have copied the files you requested. If you go into the deploy folder you can use the following scripts:

1. Start the system: ../bin/startup-linux.sh
2. Bring down the system: ../bin/teardown-linux.sh 

Please let me know if you need anything further.

Regards

**Comment by EduJGURJC** [comment]
Hi,

great! thank you @sgioldasis

Regards
