### ISSUE TITLE
latest tag for edm images

### ISSUE THREAD

**Issue by EduJGURJC** [elastest/elastest-data-manager#5]
Hi,

It would be convenient push latest tag for each edm image.

Thank you.

**Comment by sgioldasis** [comment]
Hi,

I have changed the Jenkinsfile and both the docker-compose.yml (in root and deploy folders) to use latest images.

Please check and let me know if you need anything else.

Regards

**Comment by EduJGURJC** [comment]
Hi,

it's working correctly.

Thank you
